//you can test out html requests here
//install the rest client extension for vscode



//GET http://localhost:4000/ HTTP/1.1
//content-type: application/json

//use the request above as a sanity check
//if the backend server is running correctly
//will return "Hello World!



GET http://localhost:4000/events HTTP/1.1
content-type: application/json



